operator:
    address: 0xcf17Ea5ef0b2D6DDe9AB719cf986747990c55C11
    earnings_receiver_address: 0xcf17Ea5ef0b2D6DDe9AB719cf986747990c55C11
    delegation_approver_address: "0x0000000000000000000000000000000000000000"
    staker_opt_out_window_blocks: 0
    metadata_url: "https://raw.githubusercontent.com/saisoma123/blockpost-avs/main/config/metadata.json"
el_delegation_manager_address: 0xA44151489861Fe9e3055d95adC98FbD462B948e7
eth_rpc_url: https://ethereum-holesky-rpc.publicnode.com
private_key_store_path: /home/saisoma123/blockpost-avs/.eigenlayer/operator_keys/BlockPostECDSA.ecdsa.key.json
signer_type: local_keystore
chain_id: 17000
fireblocks:
    api_key: ""
    secret_key: ""
    base_url: "https://api.fireblocks.io/"
    vault_account_name: ""
    secret_storage_type: ""
    aws_region: ""
    timeout: 3
web3:
    url: ""
